subjects = ["sub-04" "sub-05" "sub-06" ...
	"sub-07" "sub-08" "sub-09" "sub-10" "sub-11" "sub-12" ...
	"sub-13" "sub-14" "sub-15" "sub-16" "sub-17" "sub-19" ...
	"sub-20" "sub-21" "sub-22" "sub-23" "sub-24" "sub-25" ...
	"sub-27" "sub-29"];
sessions = ["run-1" "run-2" "run-3"];
dmn_ic = [11 10 12];

n_subjects = length(subjects);
n_sessions = length(sessions);

data_in = ["dr_stage2_subject00000_Z.nii.gz" ...
    "dr_stage2_subject00001_Z.nii.gz" ...
    "dr_stage2_subject00002_Z.nii.gz" ...
    "dr_stage2_subject00003_Z.nii.gz" ...
    "dr_stage2_subject00004_Z.nii.gz" ...
    "dr_stage2_subject00005_Z.nii.gz" ...
    "dr_stage2_subject00006_Z.nii.gz" ...
    "dr_stage2_subject00007_Z.nii.gz" ...
    "dr_stage2_subject00008_Z.nii.gz" ...
    "dr_stage2_subject00009_Z.nii.gz" ...
    "dr_stage2_subject00010_Z.nii.gz" ...
    "dr_stage2_subject00011_Z.nii.gz" ...
    "dr_stage2_subject00012_Z.nii.gz" ...
    "dr_stage2_subject00013_Z.nii.gz" ...
    "dr_stage2_subject00014_Z.nii.gz" ...
    "dr_stage2_subject00015_Z.nii.gz" ...
    "dr_stage2_subject00016_Z.nii.gz" ...
    "dr_stage2_subject00017_Z.nii.gz" ...
    "dr_stage2_subject00018_Z.nii.gz" ...
    "dr_stage2_subject00019_Z.nii.gz" ...
    "dr_stage2_subject00020_Z.nii.gz" ...
    "dr_stage2_subject00021_Z.nii.gz" ...
    "dr_stage2_subject00022_Z.nii.gz"];

cross_dice = zeros(n_sessions);
cross_dice_subjs = zeros(n_sessions, n_sessions, n_subjects);

for s = 1 : n_subjects

	subject = subjects(s);

	for se1 = 1 : n_sessions

		path_data_in = strcat('PARIS\DATA\func\', subject, '\task-rest\', sessions(se1));
		img1 = niftiread(fullfile(path_data_in, data_in(s)));
		img1 = img1(:, :, :, dmn_ic(se1));
        img1(img1 < 3) = 0; img1(img1 >= 3) = 1; img1 = double(img1);

		for se2 = se1 : n_sessions

			path_data_in = strcat('PARIS\DATA\func\', subject, '\task-rest\', sessions(se2));
			img2 = niftiread(fullfile(path_data_in, data_in(s)));
			img2 = img2(:, :, :, dmn_ic(se2));
            img2(img2 < 3) = 0; img2(img2 >= 3) = 1;
            img2 = double(img2);

			cross_dice(se1, se2) = dice(img1(:), img2(:));

		end %se2		

	end %se1

	cross_dice_subjs(:, :, s) = cross_dice;
    clear img1 img2 

end %subjects

cross_dice_box = reshape(cross_dice_subjs, [n_sessions*n_sessions n_subjects]);
cross_dice_box(9, :) = []; cross_dice_box(5:6, :) = [];
cross_dice_box(1:3, :) = []; 

figure;
set(groot, 'defaultFigureUnits','centimeters');
set(groot, 'defaultFigurePosition', [0 0 22 30]);
b = boxplot(cross_dice_box', 'Colors', [0 0.4470 0.7410]);
set(b, {'linew'}, {2}); 
ax = gca; 
ax.XGrid = 'off'; ax.YGrid = 'on';
ax.YAxis.FontSize = 16;
set(gca,'XTickLabel', {'run-1 vs. run-2', 'run-1 vs. run-3', ...
    'run-2 vs. run-3'}, 'FontSize', 22);
ylabel('Dice Coef.', 'FontSize', 22);



